name: ip_pomoshnik_kz
description: Flutter MVP for ИП Казахстана
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
